### PR TITLE
Add support for compatible release ranges

### LINKED ISSUE #37: Support compatible release clauses (~=)
Hi!
Here's an example:
```python
Spec('~=1.5.6') # results in a ValueError
```

https://www.python.org/dev/peps/pep-0440/#compatible-release

### PR DESCRIPTION
**Pull request by ekmartin**
Fixes #37

### CODE REVIEW

**Comment by ekmartin** [comment]
Sorry, had a typo that failed one of the tests - should be good now.

**Comment by rbarrois** [comment]
Awesome, thanks!

Could you add an entry in the docs? It should go around https://github.com/rbarrois/python-semanticversion/blob/master/docs/reference.rst#version-specifications-the-spec-class, near the note about NPM (sorry, github doesn't allow to view source code of RST files...)

**Comment by ekmartin** [comment]
Sure, I'll take a look at it tomorrow.

**Comment by rbarrois** [comment]
[ @MinchinWeb : Yes, but it doesn't allow to point at specific lines :P ]

**Pull request merged**
