### PR TITLE
alter carat matching to mirror NPM behavior

### PR DESCRIPTION
**Pull request by paulortman**
NPM does not consider prereleases (-alpha, -rc1, -beta) when matching
using the carat (^) specifier. This change alters behavior to match
that of NPM.

Addresses issue #61

### CODE REVIEW

**Comment by davegaeddert** [comment]
May also be worth adding a couple new test cases, particularly those that have a pre-release in the spec where it looks like it *would* include pre-releases >= the spec:
image

**Comment by ivankravets** [comment]
@rbarrois have you abandoned this project? Could you grant permissions to this repository the active contributors? Thanks!

**Comment by jayvdb** [comment]
Try restarting https://travis-ci.org/rbarrois/python-semanticversion/jobs/297076406

The same job passed on my PR.

**Comment by rbarrois** [comment]
Hey,

Sorry for the late reaction; this feature has been included as part of the "multiple syntaxes available" rework; the ``NpmSpec`` should now offer a fully-compliant implementation of the NPM range syntax :)

**Pull request closed without merging**
